# Generated by Django 3.2 on 2021-06-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(db_column='que_id', primary_key=True, serialize=False)),
                ('nom', models.CharField(db_column='que_nom', max_length=255)),
                ('quartier', models.CharField(db_column='que_quartier', max_length=255)),
                ('quartier_futur', models.CharField(blank=True, db_column='que_quartier_futur', max_length=255, null=True)),
                ('org_ville_demain', models.TextField(db_column='que_org_ville_demain', max_length=255)),
                ('hum_ville_demain', models.CharField(blank=True, db_column='que_hum_ville_demain', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Questionnaire',
                'ordering': ['id'],
            },
        ),
    ]
