# Generated by Django 3.2 on 2021-06-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire_affiche',
            fields=[
                ('id', models.AutoField(db_column='que_id', primary_key=True, serialize=False)),
                ('quartier_a', models.CharField(db_column='que_quartier_a', max_length=255)),
                ('quartier_futur_a', models.CharField(blank=True, db_column='que_quartier_futur_a', max_length=255, null=True)),
                ('org_ville_demain_a', models.TextField(db_column='que_org_ville_demain_a', max_length=255)),
                ('hum_ville_demain_a', models.CharField(blank=True, db_column='que_hum_ville_demain_a', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Questionnaire_affiche',
                'verbose_name_plural': 'Questionnaires_affiches',
                'ordering': ['id'],
            },
        ),
    ]
